# Link for Data:  https://www.kaggle.com/c/fake-news/data

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("train.csv")

In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
# Drop NAN values
df= df.dropna()

In [ ]:
df.shape

(18285, 5)

In [ ]:
X = df.drop('label', axis=1)

In [ ]:
y= df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf 

In [ ]:
tf.__version__

'2.3.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [40]:
voc_size= 5000

## One-Hot Representation


In [ ]:
messages = X.copy()

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages.shape

(18285, 5)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords 

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [29]:
## Data Preprocessing
from nltk.stem import PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range (0, len(messages)):
  print(i) 
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [30]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [31]:
onehot_repre = [one_hot(words, voc_size) for words in corpus]
onehot_repre

[[2874, 150, 1774, 4103, 447, 643, 946, 3573, 4781, 320],
 [4042, 34, 4461, 925, 896, 3738, 4595],
 [4524, 1484, 1219, 205],
 [2544, 2141, 4456, 3803, 2257, 1494],
 [385, 896, 4131, 576, 1559, 733, 896, 4577, 1301, 2382],
 [3536,
  2184,
  3054,
  259,
  3677,
  4357,
  4227,
  2989,
  151,
  4937,
  4297,
  3943,
  4066,
  2574,
  4595],
 [843, 2853, 1851, 1806, 3915, 724, 4143, 380, 4312, 1820, 394],
 [4613, 4739, 4436, 328, 2331, 919, 4357, 2714, 4312, 1820, 394],
 [248, 905, 1998, 2208, 185, 1820, 3730, 2171, 4357, 1580],
 [3794, 666, 2470, 2006, 2895, 323, 1423, 3561],
 [2727, 3422, 2978, 2211, 2403, 4106, 4843, 418, 977, 2399, 2905],
 [3803, 3161, 447, 1820, 4357, 2331],
 [4937, 4718, 757, 1521, 4497, 2668, 465, 125, 503],
 [4615, 403, 2701, 4138, 2836, 1787, 2325, 4312, 1820, 394],
 [4169, 1074, 3797, 1992, 4586, 4312, 1820, 394],
 [4828, 2836, 3337, 497, 1065, 330, 3648, 4572, 4032, 3639],
 [2187, 1066, 34],
 [1722, 3561, 1342, 1887, 4357, 3944, 3160, 4595],
 [1484, 2934, 4461,

## Embedding Representation

In [32]:
sent_length = 20
embedded_doc = pad_sequences(onehot_repre, padding='pre', maxlen=sent_length)
print(embedded_doc)

[[   0    0    0 ... 3573 4781  320]
 [   0    0    0 ...  896 3738 4595]
 [   0    0    0 ... 1484 1219  205]
 ...
 [   0    0    0 ... 4312 1820  394]
 [   0    0    0 ... 2602  793 2082]
 [   0    0    0 ... 3597 2091 2838]]


In [34]:
len(embedded_doc)

18285

In [35]:
embedded_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2874,
        150, 1774, 4103,  447,  643,  946, 3573, 4781,  320], dtype=int32)

## Creating the Model

In [47]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [48]:
y.shape, len(embedded_doc)

((18285,), 18285)

In [49]:
import numpy as np
X_final = np.array(embedded_doc)
y_final = np.array(y)

In [50]:
X_final.shape,  y_final.shape

((18285, 20), (18285,))

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X_final, y_final, test_size=0.33, random_state=42)

## Model Training

In [54]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 5s 27ms/step - loss: 0.3444 - accuracy: 0.8371 - val_loss: 0.2009 - val_accuracy: 0.9138
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1399 - accuracy: 0.9435 - val_loss: 0.2013 - val_accuracy: 0.9186
Epoch 3/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0953 - accuracy: 0.9648 - val_loss: 0.2297 - val_accuracy: 0.9170
Epoch 4/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0638 - accuracy: 0.9771 - val_loss: 0.2762 - val_accuracy: 0.9162
Epoch 5/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0402 - accuracy: 0.9862 - val_loss: 0.3432 - val_accuracy: 0.9115
Epoch 6/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0228 - accuracy: 0.9922 - val_loss: 0.4092 - val_accuracy: 0.9112
Epoch 7/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0145 - accuracy: 0.9955 - val_loss: 0.4323 - val_accuracy: 0.9135

## Performance Metrics and Accuracy

In [55]:
y_pred=model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3125,  294],
       [ 237, 2379]])

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.912013256006628

## After adding Dropout

In [62]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [63]:
y_pred=model.predict_classes(X_test)

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1089, 2330],
       [1515, 1101]])

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.3628831814415907

#### After adding the dropout the accuracy decreases here, and it will keep changing on executing it every time